 - name: Reboot the invader
   shell: "redis-cli -h {{ bmc_redis_ip }} hset platina-mk1-bmc psu.powercycle true"

 - name:  Wait for few seconds for bgp to establish connection
   pause:
     seconds: 120

 - include: ../get_goes_status.yml 

 - name: Verify frr status
   command: "service frr status"
   register: frr_status

 - debug: 
     msg: "FRR service is in active state"
   when: "' Active: active ' in frr_status.stdout"

 - name: Verify frr bgp neighborship 
   test_bgp_authentication:
     switch_name: "{{ inventory_hostname }}"
     config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/bgp_peering_ebgp.conf') }}"
     package_name: "frr"
     hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
     log_dir_path: "{{ bgp_log_dir }}"
   register: module_out

 - file:
     path: "{{ system_restartability_log_dir }}"
     state: directory

 - command: "date +%Y%m%d%T"
   register: end_time

 - name: Fetch the log file
   slurp:
     src: "{{ module_out.log_file_path }}"
   register: logs

 - name: Store the test result in a hash in redis db on server emulator
   store_result_in_redis:
     hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
     start_time: "{{ hostvars['server_emulator']['start_time'] }}"
     end_time: "{{ end_time.stdout }}"
     hash_dict: "{{ module_out.hash_dict }}"
     log_content: "{{ logs['content'] | b64decode }}"
   delegate_to: 127.0.0.1
