---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version
      when: not dry_run

    - debug:
        var: kernel_version.stdout_lines
      when: not dry_run


- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "regress_flow_control_with_10g_port_provision_single_interface_2_devices_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf[0]:spine[0]
  become: true
  tasks:
    - file:
        path: "{{ flow_control_log_dir }}"
        state: directory
      when: not dry_run

    - name: Copy port provisioned interfaces_flow_control_10g_single_interface_two_devices file to /etc/network/interfaces
      template:
        src: "../../files/{{ inventory_hostname }}/interfaces_flow_control_10g_single_interface_two_devices
        dest: "{{ network_interfaces_file }}"
      when: not dry_run

    - name: Copy goesd-platina-mk1-modprobe.conf file
      template:
        src: "../../files/{{ inventory_hostname }}/goesd-platina-mk1-modprobe.conf_flow_control_10g_single_interface_two_devices
        dest: "{{ goesd_modprobe_file }}"
      when: not dry_run
   
    - name: Update interfaces file for fiber ports
      test_fiber_ports:
        cmd : "1,1,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
      register: fmodule_out
