---

- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - shell: dpkg --list | grep kernel
      register: kernel_version

    - debug:
        var: kernel_version.stdout_lines


- hosts: leaf:spine
  become: true
  ignore_errors: yes
  tasks:
    - name: Copy bmc_downgrade script
      template:
        src: ../../templates/bmc_downgrade.sh
        dest: "/tmp/bmc_downgrade_{{ inventory_hostname }}.sh"
        mode: 0755
      delegate_to: 127.0.0.1

    - name: Run bmc_downgrade script
      shell: "./bmc_downgrade_{{ inventory_hostname }}.sh"
      args:
        chdir: /tmp/
      register: downgrade
      delegate_to: 127.0.0.1

    - debug:
        msg: "BMC successfully Downgraded"
      when: downgrade.stdout.find('Starting kernel') != -1
    
    - debug:
        msg: "BMC latest version already installed"
      when: downgrade.stdout.find('not newer') != -1

    - name: Remove bmc_downgrade script
      file:
        path: "/tmp/bmc_downgrade_{{ inventory_hostname }}.sh"
        state: absent
      delegate_to: 127.0.0.1

    - name: reboot the switch
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for switch to come back after reboot
      local_action: wait_for host={{ ansible_ssh_host }} state=started port=22 delay=30 timeout=300 connect_timeout=15


    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "BMC Downgrade: BMC successfully Downgraded"
      delegate_to: 127.0.0.1
      when: downgrade.stdout.find('Starting kernel') != -1

- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml

    - name: Verify link status b/w invaders
      verify_links:
        switch_name: "{{ inventory_hostname }}"
        leaf_list: "{{ groups['leaf'] }}"
        eth_list: "1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31"
        platina_redis_channel: "{{ platina_redis_channel }}"
      register: module_out

    - name: Print Link Status
      debug:
        var: module_out

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "Links Status {{ inventory_hostname }}: {{ module_out.msg }}"
      delegate_to: 127.0.0.1
