---
- hosts: leaf[1]:spine[1]
  become: true
  ignore_errors: yes
  tasks:
    - name: delete an existing black_hole route
      add_del_blackhole_route:
        eth_list: "5"
        switch_name: "{{ inventory_hostname }}"
        delete: True
        subnet_mask: "24"
        log_dir_path: "{{ blackhole_route_dir }}"
      when: not dry_run

    - name: Restart networking
      command: "service networking restart"
      when: not dry_run

    - name: Networking status
      command: "service networking status"
      register: network_status
      when: not dry_run

    - debug:
        msg: "Invader service is in active state"
      when: "' Active: active ' in network_status.stdout"
