---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/bird/bird.conf
      copy:
        src: "{{ bird_conf_file_bck }}"
        dest: "{{ bird_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ bird_conf_file_bck }}"
        state: absent

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'rmmod platina-mk1'
      - 'modprobe platina-mk1 provision=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1'
      - 'ifdown -a --allow vnet'
      - 'ifup -a --allow vnet'
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10

    - name: Restart bird
      service:
        name: bird
        state: restarted
