---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "bird_bgp_peering_traffic_test_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Take backup of /etc/bird/bird.conf
      copy:
        src: "{{ bird_conf_file }}"
        dest: "{{ bird_conf_file_bck }}"
        remote_src: true

    - name: Add bgp config in /etc/bird/bird.conf
      copy:
        src: ../../files/{{inventory_hostname}}/bird_bgp_peering_ebgp_loopback.conf
        dest: "{{ bird_conf_file }}"


- hosts: leaf[0]
  become: true
  tasks:
    - name: Add static routes
      command: "{{ item }}"
      with_items:
      - route add -net 192.168.42.0/24 gw 10.0.21.32
      - route add -net 192.168.43.0/24 gw 10.0.7.31
      ignore_errors: yes


- hosts: leaf[1]
  become: true
  tasks:
    - name: Add static routes
      command: "{{ item }}"
      with_items:
      - route add -net 192.168.42.0/24 gw 10.0.3.32
      - route add -net 192.168.43.0/24 gw 10.0.19.31
      ignore_errors: yes


- hosts: spine[0]
  become: true
  tasks:
    - name: Add static routes
      command: "{{ item }}"
      with_items:
      - route add -net 192.168.44.0/24 gw 10.0.19.30
      - route add -net 192.168.45.0/24 gw 10.0.7.29
      ignore_errors: yes


- hosts: spine[1]
  become: true
  tasks:
    - name: Add static routes
      command: "{{ item }}"
      with_items:
      - route add -net 192.168.44.0/24 gw 10.0.3.30
      - route add -net 192.168.45.0/24 gw 10.0.21.29
      ignore_errors: yes


- hosts: leaf:spine
  become: true
  tasks:
    - name: Restart bird
      service:
        name: bird
        state: restarted

    - name: Wait for few seconds for bgp convergence
      pause:
        seconds: 35

    - file:
        path: "{{ bgp_log_dir }}"
        state: directory

    - name: Verify bird bgp peering ebgp loopback
      test_bird_peering:
        switch_name: "{{ inventory_hostname }}"
        config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/bird_bgp_peering_ebgp_loopback.conf') }}"
        package_name: "bird"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1


- hosts: spine
  become: true
  tasks:
    - name: Copy iperf parallel server shell script
      copy:
        src: ../../files/iperf-parallel-servers
        dest: ~/iperf-parallel-servers.sh
        mode: 0755

    - name: Start iperf server instances
      shell: "~/iperf-parallel-servers.sh 4 server-report"

    - name: Initiate iperf client and verify traffic
      verify_iperf_traffic_for_dummy:
        switch_name: "{{ inventory_hostname }}"
        switch_list: "{{ groups['spine'] }}"
        packet_size_list: "100,500,1500,12000"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ bgp_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - name: Stop iperf server instances
      command: "pkill iperf"

    - shell: "rm ~/iperf-parallel-servers.sh"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_version_and_tags.yml


- include: bird_bgp_traffic_test_reset.yml
  when: reset_config


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"

    - lineinfile:
        path: "{{ regression_summary_report }}"
        line: "{{ hash_name }}: {{ result.result_status }}"


- hosts: leaf:spine
  become: true
  tasks:
    - include: ../../playbooks/get_goes_status.yml start_time={{ hostvars['server_emulator']['start_time'] }} hash_name={{ hostvars['server_emulator']['hash_name'] }}
