---

- hosts: leaf[0]
  become: true
  tasks:
    - name: Stop iperf server instances
      command: "pkill iperf"

    - shell: "rm ~/iperf-parallel-servers.sh"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/frr/bgpd.conf
      copy:
        src: "{{ frr_bgp_conf_file_bck }}"
        dest: "{{ frr_bgp_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ frr_bgp_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Execute commands
      command: "{{ item }}"
      with_items:
      - 'goes restart'

    - name: Wait few seconds for GOES to come up
      pause:
        seconds: 10

    - name: Restart frr
      service:
        name: frr
        state: restarted
