---

# Reset invaders
- include: playbooks/master_reset_invaders.yml


# Run all docker containerized test cases
- include: playbooks/docker/quagga_ospf_traffic.yml

- include: playbooks/docker/quagga_ospf_traffic_vlan.yml

- include: playbooks/docker/quagga_ospf_traffic_subports.yml
