---

- hosts: leaf:spine
  become: true
  tasks:
    - name: Get goes status
      command: goes status
      register: goes

    - name: Print goes status
      debug:
        var: goes.stdout

    - name: Get GoES version details
      shell: "goes version"
      register: goes_version

    - name: Print GoES version details
      debug:
        var: goes_version.stdout_lines

    - name: Get GoES tag details
      shell: "goes vnetd -version"
      register: goes_tags

    - name: Print GoES tag details
      debug:
        var: goes_tags.stdout_lines

    - name: Get kernel version info
      shell: dpkg --list | grep kernel
      register: kernel_version

    - name: Print kernel version info
      debug:
        var: kernel_version.stdout_lines

    - set_fact:
        goes_version: "{{ goes_version.stdout }}"
        goes_tags: "{{ goes_tags.stdout }}"
        kernel_version: "{{ kernel_version.stdout }}"


- hosts: server_emulator
  become: true
  gather_facts: no
  tasks:
    - name: Summarize the regerssion suite result
      summarize_regression:
        testbed_name: "{{ testbed_name }}"
      register: out

    - set_fact:
        build: "{{ build_no }}"
        toe: "{{ time }}"
        passed_count: "{{ out.passed_count }}"
        passed_list: "{{ out.passed_list }}"
        failed_count: "{{ out.failed_count }}"
        failed_list: "{{ out.failed_list }}"
        skipped_count: "{{ out.skipped_count }}"
        skipped_list: "{{ out.skipped_list }}"
        leaf_list: "{{ groups['leaf'] }} "
        spine_list: "{{ groups['spine'] }}"
        goes_version: "{{ hostvars['leaf[0]']['goes_version'] }}, {{ hostvars['leaf[1]']['goes_version'] }}, {{ hostvars['spine[0]']['goes_version'] }}, {{ hostvars['spine[1]']['goes_version'] }},"
        goes_tags: "{{ hostvars['leaf[0]']['goes_tags'] }}, {{ hostvars['leaf[1]']['goes_tags'] }}, {{ hostvars['spine[0]']['goes_tags'] }}, {{ hostvars['spine[1]']['goes_tags'] }},"
        kernel_version: "{{ hostvars['leaf[0]']['kernel_version'] }}, {{ hostvars['leaf[1]']['kernel_version'] }}, {{ hostvars['spine[0]']['kernel_version'] }}, {{ hostvars['spine[1]']['kernel_version'] }},"

    - name: Create the html email content
      template:
        src: "templates/email_body.j2"
        dest: "/tmp/email_body"

    - copy:
        src: "files/logs.html"
        dest: "/var/www/html/logs.html"

    - template:
        src: "templates/passed_list.j2"
        dest: "/var/www/html/passed_list_{{ build }}.html"

    - template:
        src: "templates/failed_list.j2"
        dest: "/var/www/html/failed_list_{{ build }}.html"

    - template:
        src: "templates/skipped_list.j2"
        dest: "/var/www/html/skipped_list_{{ build }}.html"


